language: python
python:
  - "2.7"
notifications:
  email: false

# install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install coveralls
  - python setup.py build_ext --inplace


# command to run tests
script: nosetests --with-coverage --cover-package=philharmonic --logging-level=INFO --with-yanc --exclude-dir-file=philharmonic/tests/exclude.txt

# calculate coverage
after_success:
  - coveralls
