from .baseprod import *

output_folder = os.path.join(base_output_folder, "ga/")

gaconf = {
    "population_size": 20,
    "recombination_rate": 0.15,
    "mutation_rate": 0.05,
    "max_generations": 20,
    "random_recreate_ratio": 0.8,
    "no_temperature": False,
    "no_el_price": False,
    # apply a hybrid GA/greedy algorithm, where
    # greedy hard constraint resolution is attempted
    # on the best schedule generated by the GA
    "greedy_constraint_fix": True,
}

if production_settings:
    gaconf["population_size"] = 100
    gaconf["max_generations"] = 100

factory['scheduler'] = "GAScheduler"
factory['scheduler_conf'] = gaconf
